POST http://localhost:3000/Productos/1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTm9tYnJlIjoiRGlzcmFlbHkiLCJVc3VhcmlvIjoiZGlzcmFlbHlwIiwiUm9sZSI6eyJJRCI6MSwiRGVzY3JpcGNpb24iOiJBZG1pbmlzdHJhZG9yIn0sIkFjdGl2byI6dHJ1ZSwiaWF0IjoxNjQzMTQyODg1fQ.yHeO3v9jactro2neq83PSgSc_ocnxOlOomT8aiTQNek",
    "Nombre": "Leslie",
    "Password": "12345",
    "Usuario": "leslie",
    "Activo": true,
    "Role": "Administrador"
}