POST http://localhost:3001/Pedidos
Content-Type: application/json

{
    "Vendedor": "Disraely",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTm9tYnJlIjoiTGVzbGllIiwiVXN1YXJpbyI6Imxlc2xpZSIsIlJvbGUiOiJBZG1pbmlzdHJhZG9yIiwiQWN0aXZvIjp0cnVlLCJpYXQiOjE2NDUwMjcwMzR9.2AW-l7m-ZXpk_1oFRXphAukyL4sk487SOxnq_6uNKoc",
    "Cliente": 1,
    "Productos": [
        {
            "Producto": 1,
            "Cantidad": 100,
            "Categoria": "Precio 1"
        },
        {
            "Producto": 2,
            "Cantidad": 100,
            "Categoria": "Precio 3"
        }
    ]
}