PUT http://localhost:3001/Productos/2
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MSwiTm9tYnJlIjoiTGVzbGllIiwiVXN1YXJpbyI6Imxlc2xpZSIsIlJvbGUiOiJBZG1pbmlzdHJhZG9yIiwiQWN0aXZvIjp0cnVlLCJpYXQiOjE2NDUwMjcwMzR9.2AW-l7m-ZXpk_1oFRXphAukyL4sk487SOxnq_6uNKoc",
    "CodigoBarra": "xxxx",
    "Descripcion": "Producto de prueba",
    "Categoria": "Golosinas",
    "Origen": "Nacional",
    "Precios": [
        {
            "Precio": 333, 
            "Categoria": "Precio 1", 
            "Impuesto": 100
        }, 
        {
            "Precio": 222, 
            "Categoria": "Precio 2", 
            "Impuesto": 100
        },
        {
            "Precio": 222, 
            "Categoria": "Precio 3", 
            "Impuesto": 100
        },
        {
            "Precio": 222, 
            "Categoria": "Precio 4", 
            "Impuesto": 100
        }
    ]
}